name: Daily Penalty Check

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:     # Allow manual run from GitHub UI

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Penalty Check API
        run: |
          curl -X GET https://kiyaequb-tempo.vercel.app/api/penalty/check
